spring:
  application:
    name: twitter
server:
  port: 8082

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
